language: node_js
node_js:
- '10'
sudo: false
install:
- npm install --only=dev
- npm ci
before_script:
- node node_modules/eslint/bin/eslint.js .
script:
- node ./edenconfig.js
after_script:
- npm test
deploy:
  provider: npm
  email: alex@edenup.com
  api_key:
    secure: l8k3KpaecKCVSdmGzhcPnZCr5u0O/NF60lWAPaYD/akgrO3ERYdjPnfljL8L6LxT01IhtH27ErDjJKydAGxCwoPCIy6C5OgBwZ8hKVm2UlwwdqnRSJ+NcbQkAuRazX/Sm8whVd6QGZc9WHiXFruB2k2ZHtaEmgvR5jrFJ1s4+Zyhb9d3IEtKuXXJNIvWATtjALwmC6VT0WE5W6GBiEVvqTch/t+qa8YBYWrLh49YKS7DTaThRCsiFVr8atai4ezm7qecDFMdzrLuxBnrht6+9fheM+pQPxOJIyzOrMkVkTKHt045j1RzyQDKVgH6vfWp8p90M4OZejoOffW7aFm5UCp5u0u4wveS3dCL+1WHa40yvgVscg3Keit+zcNoj0al65axDFFtCgVya/WgQl0Hz4BT5k46loWqCcyFy44cm57Lq499+Ot+gCytEslykzMluEKYGeIK4iSY3P32rVJskoBCiZb0k+ll0wa5bVv/nSquqE5zm0+2VEb3a1XKLpq7dRikUH8vKipfAwth9HJKRmyQveNqny+UrZgR/Gc16YWn/hLVUCOuVCDa5dUFZX8uqwkzhPyfFqHlIpDMxE3toqCOYHx5Do3KXQwaffdGDC3UWkGw+1B8oihK0PQzhuABpiOP/708MFQRFkFXBvq3CiyR7ywsC2WbcCoTn0yCfTY=
  on:
    tags: true
    repo: ifactorydigital/ifactoryjs_riot
